-- The stock core: movement documents (the user-facing papers), the
-- immutable stock ledger, and the mutable per-item×warehouse level cache.
-- The ledger answers "how did we get here" (audit, valuation history);
-- the level answers "what is on hand right now" and is the concurrency
-- gate — it is read FOR UPDATE and maintained in the same transaction as
-- every ledger append. Batch and serial masters are dormant dimensions:
-- present so lines and ledger rows carry them from day one, enforced only
-- when their feature phases land.

-- Movement documents. Lifecycle draft -> posted -> reversed, exactly like
-- accounting_journal_entries. move_type: receipt|issue|transfer|adjustment.
CREATE TABLE inventory_moves (
    id              UUID PRIMARY KEY,
    number          TEXT,                     -- allocated at post
    move_type       TEXT NOT NULL,
    entry_date      DATE NOT NULL,
    memo            TEXT NOT NULL,
    reference       TEXT,                     -- external doc (delivery note no.)
    -- transfers use both; receipts only to_; issues only from_.
    from_warehouse_id UUID REFERENCES inventory_warehouses (id),
    to_warehouse_id   UUID REFERENCES inventory_warehouses (id),
    status          TEXT NOT NULL DEFAULT 'draft',
    -- Set when this document was generated by another (a goods receipt
    -- posting a PO): "procurement.receipt:{uuid}". Such moves reverse only
    -- through their source document.
    source          TEXT,
    reverses_id     UUID REFERENCES inventory_moves (id),
    reversed_by_id  UUID REFERENCES inventory_moves (id),
    posted_at       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID
);
CREATE UNIQUE INDEX ux_inventory_moves_number ON inventory_moves (number);
CREATE INDEX ix_inventory_moves_status_date ON inventory_moves (status, entry_date);
CREATE INDEX ix_inventory_moves_source ON inventory_moves (source) WHERE source IS NOT NULL;

-- Batch (lot) master — dormant until the batch phase.
CREATE TABLE inventory_batches (
    id            UUID PRIMARY KEY,
    item_id       UUID NOT NULL REFERENCES inventory_items (id),
    batch_no      TEXT NOT NULL,
    manufactured_on DATE,
    expires_on    DATE,
    supplier_batch_no TEXT,               -- the supplier's own lot number
    notes         TEXT,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    UUID
);
CREATE UNIQUE INDEX ux_inventory_batches_item_no ON inventory_batches (item_id, batch_no);
CREATE INDEX ix_inventory_batches_expiry ON inventory_batches (expires_on)
    WHERE expires_on IS NOT NULL;

-- Serial number master — dormant until the serial phase. status:
-- in_stock | issued | scrapped; warehouse tracks its current home.
CREATE TABLE inventory_serials (
    id            UUID PRIMARY KEY,
    item_id       UUID NOT NULL REFERENCES inventory_items (id),
    serial_no     TEXT NOT NULL,
    batch_id      UUID REFERENCES inventory_batches (id),
    warehouse_id  UUID REFERENCES inventory_warehouses (id),
    status        TEXT NOT NULL DEFAULT 'in_stock',
    warranty_until DATE,
    notes         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    UUID
);
CREATE UNIQUE INDEX ux_inventory_serials_item_no ON inventory_serials (item_id, serial_no);
CREATE INDEX ix_inventory_serials_batch ON inventory_serials (batch_id);
CREATE INDEX ix_inventory_serials_warehouse ON inventory_serials (warehouse_id, status);

CREATE TABLE inventory_move_lines (
    id           UUID PRIMARY KEY,
    move_id      UUID NOT NULL REFERENCES inventory_moves (id) ON DELETE CASCADE,
    line_no      INTEGER NOT NULL,
    item_id      UUID NOT NULL REFERENCES inventory_items (id),
    -- Quantity as entered, always positive, in the item's stock UoM.
    -- For adjustments this is the *counted* quantity; the engine computes
    -- the delta under the level lock at post time.
    qty          NUMERIC(20, 6) NOT NULL,
    entered_uom_id UUID REFERENCES inventory_uoms (id),
    -- Receipts (and adjustments up from zero) carry a cost; issues never
    -- do — the engine prices them at the running average.
    unit_cost    NUMERIC(20, 6),
    -- Dormant dimension (enforced by the batch phase):
    batch_id     UUID REFERENCES inventory_batches (id),
    memo         TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_inventory_move_lines_move ON inventory_move_lines (move_id);
CREATE INDEX ix_inventory_move_lines_item ON inventory_move_lines (item_id);
CREATE INDEX ix_inventory_move_lines_batch ON inventory_move_lines (batch_id)
    WHERE batch_id IS NOT NULL;

-- Serials on a line are many-to-many (a line of qty 5 names 5 serials).
CREATE TABLE inventory_move_line_serials (
    move_line_id UUID NOT NULL REFERENCES inventory_move_lines (id) ON DELETE CASCADE,
    serial_id    UUID NOT NULL REFERENCES inventory_serials (id),
    PRIMARY KEY (move_line_id, serial_id)
);
CREATE INDEX ix_inventory_move_line_serials_serial ON inventory_move_line_serials (serial_id);

-- The immutable stock ledger: one row per item x warehouse x posted line.
-- Never updated, never deleted; a reversal appends mirror rows. seq gives
-- a total order per database — valuation order is seq order. BY DEFAULT
-- (not ALWAYS) so SeaORM inserts that omit the column (ActiveModel seq:
-- NotSet) let Postgres assign it.
CREATE TABLE inventory_stock_ledger (
    id            UUID PRIMARY KEY,
    seq           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    move_id       UUID NOT NULL REFERENCES inventory_moves (id),
    move_line_id  UUID NOT NULL REFERENCES inventory_move_lines (id),
    item_id       UUID NOT NULL REFERENCES inventory_items (id),
    warehouse_id  UUID NOT NULL REFERENCES inventory_warehouses (id),
    batch_id      UUID REFERENCES inventory_batches (id),   -- dormant
    entry_date    DATE NOT NULL,
    qty_delta     NUMERIC(20, 6) NOT NULL,       -- signed
    qty_after     NUMERIC(20, 6) NOT NULL,       -- running, per item x warehouse
    unit_cost     NUMERIC(20, 6) NOT NULL,       -- cost applied to this delta
    value_delta   NUMERIC(20, 4) NOT NULL,       -- signed, base currency
    value_after   NUMERIC(20, 4) NOT NULL,       -- running value per item x warehouse
    posted_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_stock_ledger_item_wh_seq ON inventory_stock_ledger (item_id, warehouse_id, seq);
CREATE INDEX ix_stock_ledger_move ON inventory_stock_ledger (move_id);
CREATE INDEX ix_stock_ledger_date ON inventory_stock_ledger (entry_date);
CREATE INDEX ix_stock_ledger_batch ON inventory_stock_ledger (batch_id)
    WHERE batch_id IS NOT NULL;

-- The mutable aggregate: one row per item x warehouse, kept in the same
-- transaction as the ledger append, under FOR UPDATE. available =
-- on_hand - reserved (computed in queries, never stored).
CREATE TABLE inventory_stock_levels (
    item_id       UUID NOT NULL REFERENCES inventory_items (id),
    warehouse_id  UUID NOT NULL REFERENCES inventory_warehouses (id),
    on_hand       NUMERIC(20, 6) NOT NULL DEFAULT 0,
    reserved      NUMERIC(20, 6) NOT NULL DEFAULT 0,   -- reservations phase
    on_order      NUMERIC(20, 6) NOT NULL DEFAULT 0,   -- open PO qty
    value         NUMERIC(20, 4) NOT NULL DEFAULT 0,   -- = last value_after
    -- Per-warehouse reorder policy overrides (reorder job phase).
    reorder_level NUMERIC(20, 6),
    reorder_qty   NUMERIC(20, 6),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (item_id, warehouse_id)
);
CREATE INDEX ix_stock_levels_warehouse ON inventory_stock_levels (warehouse_id);
