//! Stock movement documents: the user-facing papers that drive the engine.
//!
//! Four document types share one lifecycle — draft (editable, unnumbered)
//! → posted (numbered gap-free, immutable, stock applied) → reversed
//! (mirrored by a linked reversal document):
//!
//! - **receipt** — stock in at a given cost (direct/opening receipt)
//! - **issue** — stock out at the running average
//! - **transfer** — out of one warehouse, into another at the issued cost
//!   (a transfer never creates or destroys value)
//! - **adjustment** — lines carry the *counted* quantity; the delta against
//!   on-hand is computed under the level lock at post time; counting up
//!   from zero needs a unit cost (this doubles as opening stock)
//!
//! Posting locks in a fixed order everywhere: the document row first, then
//! every touched level row ascending by `(item_id, warehouse_id)`, then
//! the numbering series row — so concurrent posts serialize instead of
//! deadlocking. A movement generated by another document (`source` set,
//! e.g. a procurement goods receipt) can only be reversed through that
//! source document.

use crate::scm::inventory::item::{self, uom};
use crate::scm::inventory::permissions::names;
use crate::scm::inventory::stock::{self, Movement, StockService, ledger};
use crate::scm::inventory::warehouse;
use axum::extract::{Path, Query};
use axum::routing::{get, post};
use axum::{Extension, Json, Router};
use nebula::audit::Audit;
use nebula::auth::Authz;
use nebula::error::{Error, Result};
use nebula::{Numbering, TenantDb, sea_orm};
use rust_decimal::Decimal;
use sea_orm::entity::prelude::*;
use sea_orm::{
    ConnectionTrait, DatabaseConnection, QueryOrder, QuerySelect, Set, TransactionTrait,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

/// The four kinds of stock movement document.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum MoveType {
    Receipt,
    Issue,
    Transfer,
    Adjustment,
}

impl MoveType {
    pub fn as_str(self) -> &'static str {
        match self {
            MoveType::Receipt => "receipt",
            MoveType::Issue => "issue",
            MoveType::Transfer => "transfer",
            MoveType::Adjustment => "adjustment",
        }
    }

    pub fn parse(value: &str) -> Result<Self> {
        match value {
            "receipt" => Ok(MoveType::Receipt),
            "issue" => Ok(MoveType::Issue),
            "transfer" => Ok(MoveType::Transfer),
            "adjustment" => Ok(MoveType::Adjustment),
            other => Err(Error::internal(format!("unknown move type {other:?}"))),
        }
    }

    /// The number series this document type draws from at post.
    pub fn series(self) -> &'static str {
        match self {
            MoveType::Receipt => crate::scm::RECEIPT_SERIES,
            MoveType::Issue => crate::scm::ISSUE_SERIES,
            MoveType::Transfer => crate::scm::TRANSFER_SERIES,
            MoveType::Adjustment => crate::scm::ADJUSTMENT_SERIES,
        }
    }
}

/// Where a movement document is in its lifecycle.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum MoveStatus {
    Draft,
    Posted,
    Reversed,
}

impl MoveStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            MoveStatus::Draft => "draft",
            MoveStatus::Posted => "posted",
            MoveStatus::Reversed => "reversed",
        }
    }

    pub fn parse(value: &str) -> Result<Self> {
        match value {
            "draft" => Ok(MoveStatus::Draft),
            "posted" => Ok(MoveStatus::Posted),
            "reversed" => Ok(MoveStatus::Reversed),
            other => Err(Error::internal(format!("unknown move status {other:?}"))),
        }
    }
}

/// The movement document header.
pub mod doc {
    use nebula::sea_orm;
    use sea_orm::entity::prelude::*;
    use serde::Serialize;

    #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
    #[sea_orm(table_name = "inventory_moves")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub id: Uuid,
        pub number: Option<String>,
        pub move_type: String,
        pub entry_date: Date,
        pub memo: String,
        pub reference: Option<String>,
        pub from_warehouse_id: Option<Uuid>,
        pub to_warehouse_id: Option<Uuid>,
        pub status: String,
        pub source: Option<String>,
        pub reverses_id: Option<Uuid>,
        pub reversed_by_id: Option<Uuid>,
        pub posted_at: Option<DateTimeUtc>,
        pub created_at: DateTimeUtc,
        pub created_by: Option<Uuid>,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}
    impl ActiveModelBehavior for ActiveModel {}
}

/// One line of a movement document. `qty` is always positive and in the
/// item's stock UoM; for adjustments it is the counted quantity.
pub mod line {
    use nebula::sea_orm;
    use rust_decimal::Decimal;
    use sea_orm::entity::prelude::*;
    use serde::Serialize;

    #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
    #[sea_orm(table_name = "inventory_move_lines")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub id: Uuid,
        pub move_id: Uuid,
        pub line_no: i32,
        pub item_id: Uuid,
        #[sea_orm(column_type = "Decimal(Some((20, 6)))")]
        pub qty: Decimal,
        pub entered_uom_id: Option<Uuid>,
        #[sea_orm(column_type = "Decimal(Some((20, 6)))", nullable)]
        pub unit_cost: Option<Decimal>,
        pub batch_id: Option<Uuid>,
        pub memo: Option<String>,
        pub created_at: DateTimeUtc,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}
    impl ActiveModelBehavior for ActiveModel {}
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

/// A movement line as supplied by a caller.
pub struct LineInput {
    pub item_id: Uuid,
    pub qty: Decimal,
    pub unit_cost: Option<Decimal>,
    pub entered_uom_id: Option<Uuid>,
    pub memo: Option<String>,
}

/// A new draft movement as supplied by a caller.
pub struct NewMove {
    pub move_type: MoveType,
    pub entry_date: chrono::NaiveDate,
    pub memo: String,
    pub reference: Option<String>,
    pub from_warehouse_id: Option<Uuid>,
    pub to_warehouse_id: Option<Uuid>,
    pub lines: Vec<LineInput>,
    pub created_by: Option<Uuid>,
}

/// The movement document service over one (tenant) connection.
pub struct MoveService {
    db: DatabaseConnection,
}

impl MoveService {
    pub fn new(db: DatabaseConnection) -> Self {
        Self { db }
    }

    /// Create a draft movement. Shape (warehouses per type, quantities,
    /// costs, items) is checked now; stock sufficiency only at post, when
    /// the level lock is held.
    pub async fn create_draft(&self, new: NewMove) -> Result<MoveView> {
        validate_move(&self.db, &new).await?;
        let txn = self.db.begin().await?;
        let move_id = Uuid::new_v4();
        let now = chrono::Utc::now();
        doc::ActiveModel {
            id: Set(move_id),
            number: Set(None),
            move_type: Set(new.move_type.as_str().to_string()),
            entry_date: Set(new.entry_date),
            memo: Set(new.memo.trim().to_string()),
            reference: Set(new.reference.filter(|r| !r.trim().is_empty())),
            from_warehouse_id: Set(new.from_warehouse_id),
            to_warehouse_id: Set(new.to_warehouse_id),
            status: Set(MoveStatus::Draft.as_str().to_string()),
            source: Set(None),
            reverses_id: Set(None),
            reversed_by_id: Set(None),
            posted_at: Set(None),
            created_at: Set(now),
            created_by: Set(new.created_by),
        }
        .insert(&txn)
        .await?;
        insert_lines(&txn, move_id, &new.lines).await?;
        txn.commit().await?;
        self.view(move_id).await
    }

    /// Replace a draft's header and lines wholesale. The document type is
    /// fixed at creation — a receipt cannot become an issue.
    pub async fn update_draft(&self, id: Uuid, new: NewMove) -> Result<MoveView> {
        let txn = self.db.begin().await?;
        let existing = load_move_locked(&txn, id).await?;
        if MoveStatus::parse(&existing.status)? != MoveStatus::Draft {
            return Err(Error::Validation("only a draft movement can be edited".into()));
        }
        if MoveType::parse(&existing.move_type)? != new.move_type {
            return Err(Error::Validation(
                "a movement's type cannot change; delete the draft and create a new one".into(),
            ));
        }
        validate_move(&txn, &new).await?;

        line::Entity::delete_many()
            .filter(line::Column::MoveId.eq(id))
            .exec(&txn)
            .await?;
        insert_lines(&txn, id, &new.lines).await?;

        let mut active: doc::ActiveModel = existing.into();
        active.entry_date = Set(new.entry_date);
        active.memo = Set(new.memo.trim().to_string());
        active.reference = Set(new.reference.filter(|r| !r.trim().is_empty()));
        active.from_warehouse_id = Set(new.from_warehouse_id);
        active.to_warehouse_id = Set(new.to_warehouse_id);
        active.update(&txn).await?;
        txn.commit().await?;
        self.view(id).await
    }

    /// Delete a draft (lines cascade). Posted history is never deleted.
    pub async fn delete_draft(&self, id: Uuid) -> Result<MoveView> {
        let view = self.view(id).await?;
        let txn = self.db.begin().await?;
        let existing = load_move_locked(&txn, id).await?;
        if MoveStatus::parse(&existing.status)? != MoveStatus::Draft {
            return Err(Error::Validation("only a draft movement can be deleted".into()));
        }
        doc::Entity::delete_by_id(id).exec(&txn).await?;
        txn.commit().await?;
        Ok(view)
    }

    /// Post a draft: apply every line to the stock engine, allocate the
    /// gap-free number and freeze the document — one transaction. Items
    /// are re-validated (one may have been deactivated since the draft),
    /// and every touched level row is pre-locked in ascending order before
    /// any is changed, so concurrent posts cannot deadlock.
    pub async fn post(&self, id: Uuid, numbering: &Numbering) -> Result<MoveView> {
        let txn = self.db.begin().await?;
        let doc_row = load_move_locked(&txn, id).await?;
        if MoveStatus::parse(&doc_row.status)? != MoveStatus::Draft {
            return Err(Error::Validation("only a draft movement can be posted".into()));
        }
        let move_type = MoveType::parse(&doc_row.move_type)?;
        let lines = load_lines(&txn, id).await?;
        if lines.is_empty() {
            return Err(Error::Validation("a movement needs at least one line".into()));
        }
        let (items, uoms) = load_items(&txn, &lines).await?;
        for item in items.values() {
            if !item.is_active {
                return Err(Error::Validation(format!(
                    "item {} is inactive and cannot move",
                    item.sku
                )));
            }
        }

        // Pre-lock every level this document will touch, ascending — the
        // global lock order shared with procurement's posting paths.
        let mut gates: Vec<(Uuid, Uuid)> = lines
            .iter()
            .flat_map(|l| {
                let mut pair = Vec::with_capacity(2);
                if let Some(from) = doc_row.from_warehouse_id {
                    pair.push((l.item_id, from));
                }
                if let Some(to) = doc_row.to_warehouse_id {
                    pair.push((l.item_id, to));
                }
                pair
            })
            .collect();
        gates.sort();
        gates.dedup();
        for (item_id, warehouse_id) in &gates {
            stock::lock_or_init_level(&txn, *item_id, *warehouse_id).await?;
        }

        for l in &lines {
            let item = &items[&l.item_id];
            let stock_uom = uoms.get(&item.uom_id).ok_or_else(|| {
                Error::internal(format!("stock uom missing for item {}", item.sku))
            })?;
            apply_line(&txn, &doc_row, move_type, l, item, stock_uom).await?;
        }

        let number = numbering.next(&txn, move_type.series()).await?;
        let mut active: doc::ActiveModel = doc_row.into();
        active.status = Set(MoveStatus::Posted.as_str().to_string());
        active.number = Set(Some(number.formatted));
        active.posted_at = Set(Some(chrono::Utc::now()));
        active.update(&txn).await?;
        txn.commit().await?;
        self.view(id).await
    }

    /// Reverse a posted movement: a new document of the same type whose
    /// ledger rows mirror the original's exactly — receipts go back out,
    /// issues come back in at the cost they left at. The mirror runs
    /// through the engine, so reversing a receipt whose stock has since
    /// been issued fails the negative-stock check instead of corrupting
    /// the ledger. Documents generated by a source (a procurement goods
    /// receipt) must be reversed through that source instead.
    pub async fn reverse(
        &self,
        id: Uuid,
        reason: &str,
        entry_date: Option<chrono::NaiveDate>,
        numbering: &Numbering,
        created_by: Option<Uuid>,
    ) -> Result<MoveView> {
        let txn = self.db.begin().await?;
        let original = load_move_locked(&txn, id).await?;
        match MoveStatus::parse(&original.status)? {
            MoveStatus::Posted => {}
            MoveStatus::Draft => {
                return Err(Error::Validation(
                    "a draft movement has not been posted and cannot be reversed".into(),
                ));
            }
            MoveStatus::Reversed => {
                return Err(Error::Validation("movement is already reversed".into()));
            }
        }
        if let Some(source) = &original.source {
            return Err(Error::Validation(format!(
                "this movement was generated by {source} and must be reversed through it"
            )));
        }
        let move_type = MoveType::parse(&original.move_type)?;

        let now = chrono::Utc::now();
        let reversal_date = entry_date.unwrap_or_else(|| now.date_naive());
        if reversal_date < original.entry_date {
            return Err(Error::Validation(
                "a reversal cannot be dated before the movement it reverses".into(),
            ));
        }

        let original_lines = load_lines(&txn, id).await?;
        let rows = ledger::Entity::find()
            .filter(ledger::Column::MoveId.eq(id))
            .order_by_asc(ledger::Column::Seq)
            .all(&txn)
            .await?;
        let (items, uoms) = load_items(&txn, &original_lines).await?;

        // Pre-lock the touched levels in the same ascending order as post.
        let mut gates: Vec<(Uuid, Uuid)> =
            rows.iter().map(|r| (r.item_id, r.warehouse_id)).collect();
        gates.sort();
        gates.dedup();
        for (item_id, warehouse_id) in &gates {
            stock::lock_or_init_level(&txn, *item_id, *warehouse_id).await?;
        }

        let reversal_id = Uuid::new_v4();
        let memo = if reason.trim().is_empty() {
            format!(
                "Reversal of {}",
                original.number.as_deref().unwrap_or("movement")
            )
        } else {
            format!(
                "Reversal of {}: {}",
                original.number.as_deref().unwrap_or("movement"),
                reason.trim()
            )
        };
        let number = numbering.next(&txn, move_type.series()).await?;
        doc::ActiveModel {
            id: Set(reversal_id),
            number: Set(Some(number.formatted)),
            move_type: Set(original.move_type.clone()),
            entry_date: Set(reversal_date),
            memo: Set(memo),
            reference: Set(original.number.clone()),
            from_warehouse_id: Set(original.from_warehouse_id),
            to_warehouse_id: Set(original.to_warehouse_id),
            status: Set(MoveStatus::Posted.as_str().to_string()),
            source: Set(None),
            reverses_id: Set(Some(original.id)),
            reversed_by_id: Set(None),
            posted_at: Set(Some(now)),
            created_at: Set(now),
            created_by: Set(created_by),
        }
        .insert(&txn)
        .await?;

        // Copy the lines (descriptive), then mirror each ledger row of the
        // original through the engine against the copied line.
        let mut mirror_line_ids: HashMap<Uuid, Uuid> = HashMap::new();
        let line_now = chrono::Utc::now();
        for l in &original_lines {
            let new_id = Uuid::new_v4();
            mirror_line_ids.insert(l.id, new_id);
            line::ActiveModel {
                id: Set(new_id),
                move_id: Set(reversal_id),
                line_no: Set(l.line_no),
                item_id: Set(l.item_id),
                qty: Set(l.qty),
                entered_uom_id: Set(l.entered_uom_id),
                unit_cost: Set(l.unit_cost),
                batch_id: Set(l.batch_id),
                memo: Set(l.memo.clone()),
                created_at: Set(line_now),
            }
            .insert(&txn)
            .await?;
        }

        for row in &rows {
            let item = items.get(&row.item_id).ok_or_else(|| {
                Error::internal(format!("item {} missing for reversal", row.item_id))
            })?;
            let stock_uom = uoms.get(&item.uom_id).ok_or_else(|| {
                Error::internal(format!("stock uom missing for item {}", item.sku))
            })?;
            let mirror_line = *mirror_line_ids
                .get(&row.move_line_id)
                .ok_or_else(|| Error::internal("ledger row without a document line"))?;
            let mv = if row.qty_delta > Decimal::ZERO {
                Movement::Issue { qty: row.qty_delta }
            } else {
                Movement::Receipt {
                    qty: -row.qty_delta,
                    unit_cost: row.unit_cost,
                }
            };
            StockService::apply(
                &txn,
                reversal_id,
                mirror_line,
                reversal_date,
                item,
                stock_uom,
                row.warehouse_id,
                mv,
            )
            .await?;
        }

        let mut active: doc::ActiveModel = original.into();
        active.status = Set(MoveStatus::Reversed.as_str().to_string());
        active.reversed_by_id = Set(Some(reversal_id));
        active.update(&txn).await?;

        txn.commit().await?;
        self.view(reversal_id).await
    }

    pub async fn list(&self, filter: MoveFilter) -> Result<Vec<MoveHeader>> {
        let mut query = doc::Entity::find();
        if let Some(t) = filter.move_type {
            query = query.filter(doc::Column::MoveType.eq(t.as_str()));
        }
        if let Some(s) = filter.status {
            query = query.filter(doc::Column::Status.eq(s.as_str()));
        }
        if let Some(w) = filter.warehouse_id {
            query = query.filter(
                doc::Column::FromWarehouseId
                    .eq(w)
                    .or(doc::Column::ToWarehouseId.eq(w)),
            );
        }
        if let Some(from) = filter.from {
            query = query.filter(doc::Column::EntryDate.gte(from));
        }
        if let Some(to) = filter.to {
            query = query.filter(doc::Column::EntryDate.lte(to));
        }
        let rows = query
            .order_by_desc(doc::Column::EntryDate)
            .order_by_desc(doc::Column::CreatedAt)
            .all(&self.db)
            .await?;
        rows.into_iter().map(header).collect()
    }

    /// The document type of a movement, for permission routing.
    pub async fn move_type_of(&self, id: Uuid) -> Result<MoveType> {
        let row = load_move(&self.db, id).await?;
        MoveType::parse(&row.move_type)
    }

    /// Load a full document with its lines and item/warehouse labels.
    pub async fn view(&self, id: Uuid) -> Result<MoveView> {
        let doc_row = load_move(&self.db, id).await?;
        let lines = load_lines(&self.db, id).await?;
        let (items, _) = load_items(&self.db, &lines).await?;

        let warehouse_ids: Vec<Uuid> = [doc_row.from_warehouse_id, doc_row.to_warehouse_id]
            .into_iter()
            .flatten()
            .collect();
        let warehouses: HashMap<Uuid, warehouse::Model> = warehouse::Entity::find()
            .filter(warehouse::Column::Id.is_in(warehouse_ids))
            .all(&self.db)
            .await?
            .into_iter()
            .map(|w| (w.id, w))
            .collect();
        let warehouse_ref = |id: Option<Uuid>| {
            id.and_then(|id| warehouses.get(&id)).map(|w| WarehouseRef {
                id: w.id,
                code: w.code.clone(),
                name: w.name.clone(),
            })
        };

        let line_views = lines
            .into_iter()
            .map(|l| {
                let item = items.get(&l.item_id);
                MoveLineView {
                    id: l.id,
                    line_no: l.line_no,
                    item_id: l.item_id,
                    sku: item.map(|i| i.sku.clone()).unwrap_or_default(),
                    item_name: item.map(|i| i.name.clone()).unwrap_or_default(),
                    qty: l.qty,
                    unit_cost: l.unit_cost,
                    memo: l.memo,
                }
            })
            .collect();

        Ok(MoveView {
            id: doc_row.id,
            number: doc_row.number,
            move_type: MoveType::parse(&doc_row.move_type)?,
            entry_date: doc_row.entry_date,
            memo: doc_row.memo,
            reference: doc_row.reference,
            from_warehouse: warehouse_ref(doc_row.from_warehouse_id),
            to_warehouse: warehouse_ref(doc_row.to_warehouse_id),
            status: MoveStatus::parse(&doc_row.status)?,
            source: doc_row.source,
            reverses_id: doc_row.reverses_id,
            reversed_by_id: doc_row.reversed_by_id,
            posted_at: doc_row.posted_at,
            created_at: doc_row.created_at,
            lines: line_views,
        })
    }
}

/// Apply one document line to the engine per the document's type.
async fn apply_line(
    txn: &sea_orm::DatabaseTransaction,
    doc_row: &doc::Model,
    move_type: MoveType,
    l: &line::Model,
    item: &item::item::Model,
    stock_uom: &uom::Model,
) -> Result<()> {
    match move_type {
        MoveType::Receipt => {
            let cost = l.unit_cost.ok_or_else(|| {
                Error::Validation(format!("line {} needs a unit cost", l.line_no))
            })?;
            let to = doc_row
                .to_warehouse_id
                .ok_or_else(|| Error::internal("receipt without a destination warehouse"))?;
            StockService::apply(
                txn,
                doc_row.id,
                l.id,
                doc_row.entry_date,
                item,
                stock_uom,
                to,
                Movement::Receipt {
                    qty: l.qty,
                    unit_cost: cost,
                },
            )
            .await?;
        }
        MoveType::Issue => {
            let from = doc_row
                .from_warehouse_id
                .ok_or_else(|| Error::internal("issue without a source warehouse"))?;
            StockService::apply(
                txn,
                doc_row.id,
                l.id,
                doc_row.entry_date,
                item,
                stock_uom,
                from,
                Movement::Issue { qty: l.qty },
            )
            .await?;
        }
        MoveType::Transfer => {
            let from = doc_row
                .from_warehouse_id
                .ok_or_else(|| Error::internal("transfer without a source warehouse"))?;
            let to = doc_row
                .to_warehouse_id
                .ok_or_else(|| Error::internal("transfer without a destination warehouse"))?;
            // Out at the running average, then in at exactly that cost — a
            // transfer never creates or destroys value.
            let out = StockService::apply(
                txn,
                doc_row.id,
                l.id,
                doc_row.entry_date,
                item,
                stock_uom,
                from,
                Movement::Issue { qty: l.qty },
            )
            .await?;
            StockService::apply(
                txn,
                doc_row.id,
                l.id,
                doc_row.entry_date,
                item,
                stock_uom,
                to,
                Movement::Receipt {
                    qty: l.qty,
                    unit_cost: out.unit_cost,
                },
            )
            .await?;
        }
        MoveType::Adjustment => {
            let wh = doc_row
                .from_warehouse_id
                .ok_or_else(|| Error::internal("adjustment without a warehouse"))?;
            // The line carries the counted quantity; the delta is computed
            // here, with the level lock already held.
            let level = stock::lock_or_init_level(txn, item.id, wh).await?;
            let delta = l.qty - level.on_hand;
            if delta > Decimal::ZERO {
                let cost = match l.unit_cost {
                    Some(cost) => cost,
                    None if level.on_hand.is_zero() => {
                        return Err(Error::Validation(format!(
                            "line {}: adjusting {} up from zero stock needs a unit cost",
                            l.line_no, item.sku
                        )));
                    }
                    None => stock::level_average(&level),
                };
                StockService::apply(
                    txn,
                    doc_row.id,
                    l.id,
                    doc_row.entry_date,
                    item,
                    stock_uom,
                    wh,
                    Movement::Receipt {
                        qty: delta,
                        unit_cost: cost,
                    },
                )
                .await?;
            } else if delta < Decimal::ZERO {
                StockService::apply(
                    txn,
                    doc_row.id,
                    l.id,
                    doc_row.entry_date,
                    item,
                    stock_uom,
                    wh,
                    Movement::Issue { qty: -delta },
                )
                .await?;
            }
            // delta == 0: the count matches; nothing to book.
        }
    }
    Ok(())
}

/// Draft-time validation: header shape, warehouse rules per type, line
/// quantities/costs, and that every referenced item and UoM exists.
async fn validate_move<C: ConnectionTrait>(conn: &C, new: &NewMove) -> Result<()> {
    if new.memo.trim().is_empty() {
        return Err(Error::Validation("a movement needs a memo".into()));
    }
    if new.lines.is_empty() {
        return Err(Error::Validation("a movement needs at least one line".into()));
    }

    match new.move_type {
        MoveType::Receipt => {
            if new.to_warehouse_id.is_none() || new.from_warehouse_id.is_some() {
                return Err(Error::Validation(
                    "a receipt sets to_warehouse_id only".into(),
                ));
            }
        }
        MoveType::Issue => {
            if new.from_warehouse_id.is_none() || new.to_warehouse_id.is_some() {
                return Err(Error::Validation(
                    "an issue sets from_warehouse_id only".into(),
                ));
            }
        }
        MoveType::Transfer => {
            let (Some(from), Some(to)) = (new.from_warehouse_id, new.to_warehouse_id) else {
                return Err(Error::Validation(
                    "a transfer sets both from_warehouse_id and to_warehouse_id".into(),
                ));
            };
            if from == to {
                return Err(Error::Validation(
                    "a transfer needs two different warehouses".into(),
                ));
            }
        }
        MoveType::Adjustment => {
            if new.from_warehouse_id.is_none() || new.to_warehouse_id.is_some() {
                return Err(Error::Validation(
                    "an adjustment sets from_warehouse_id only (the warehouse being counted)"
                        .into(),
                ));
            }
        }
    }

    let warehouse_ids: Vec<Uuid> = [new.from_warehouse_id, new.to_warehouse_id]
        .into_iter()
        .flatten()
        .collect();
    for id in warehouse_ids {
        let found = warehouse::Entity::find_by_id(id).one(conn).await?;
        match found {
            Some(w) if w.is_active => {}
            Some(w) => {
                return Err(Error::Validation(format!(
                    "warehouse {} is inactive",
                    w.code
                )));
            }
            None => return Err(Error::Validation(format!("warehouse {id} does not exist"))),
        }
    }

    for (i, l) in new.lines.iter().enumerate() {
        let line_no = i + 1;
        // Adjustments count what's there — zero is a valid count.
        let qty_ok = if new.move_type == MoveType::Adjustment {
            l.qty >= Decimal::ZERO
        } else {
            l.qty > Decimal::ZERO
        };
        if !qty_ok {
            return Err(Error::Validation(format!(
                "line {line_no}: quantity must be {}",
                if new.move_type == MoveType::Adjustment {
                    "zero or more"
                } else {
                    "positive"
                }
            )));
        }
        match new.move_type {
            // Issues and transfers always go out at the running average.
            MoveType::Issue | MoveType::Transfer => {
                if l.unit_cost.is_some() {
                    return Err(Error::Validation(format!(
                        "line {line_no}: {}s are costed at the running average; do not send a unit cost",
                        new.move_type.as_str()
                    )));
                }
            }
            MoveType::Receipt | MoveType::Adjustment => {
                if l.unit_cost.is_some_and(|c| c < Decimal::ZERO) {
                    return Err(Error::Validation(format!(
                        "line {line_no}: unit cost must not be negative"
                    )));
                }
            }
        }
    }

    let item_ids: Vec<Uuid> = new.lines.iter().map(|l| l.item_id).collect();
    let found: HashMap<Uuid, item::item::Model> = item::item::Entity::find()
        .filter(item::item::Column::Id.is_in(item_ids))
        .all(conn)
        .await?
        .into_iter()
        .map(|i| (i.id, i))
        .collect();
    for (i, l) in new.lines.iter().enumerate() {
        let Some(item) = found.get(&l.item_id) else {
            return Err(Error::NotFound(format!("item {}", l.item_id)));
        };
        if !item.is_active {
            return Err(Error::Validation(format!(
                "line {}: item {} is inactive",
                i + 1,
                item.sku
            )));
        }
        if let Some(uom_id) = l.entered_uom_id {
            let exists = uom::Entity::find_by_id(uom_id).one(conn).await?;
            if exists.is_none() {
                return Err(Error::Validation(format!(
                    "line {}: unit of measure {uom_id} does not exist",
                    i + 1
                )));
            }
        }
    }
    Ok(())
}

/// Insert a set of lines for a movement, numbered from one.
async fn insert_lines<C: ConnectionTrait>(
    conn: &C,
    move_id: Uuid,
    lines: &[LineInput],
) -> Result<()> {
    let now = chrono::Utc::now();
    for (i, l) in lines.iter().enumerate() {
        line::ActiveModel {
            id: Set(Uuid::new_v4()),
            move_id: Set(move_id),
            line_no: Set((i + 1) as i32),
            item_id: Set(l.item_id),
            qty: Set(l.qty),
            entered_uom_id: Set(l.entered_uom_id),
            unit_cost: Set(l.unit_cost),
            batch_id: Set(None),
            memo: Set(l.memo.clone().filter(|m| !m.trim().is_empty())),
            created_at: Set(now),
        }
        .insert(conn)
        .await?;
    }
    Ok(())
}

async fn load_move<C: ConnectionTrait>(conn: &C, id: Uuid) -> Result<doc::Model> {
    doc::Entity::find_by_id(id)
        .one(conn)
        .await?
        .ok_or_else(|| Error::NotFound(format!("stock movement {id}")))
}

/// Load a movement holding its row lock, so concurrent state transitions
/// on the same document serialize.
async fn load_move_locked(txn: &sea_orm::DatabaseTransaction, id: Uuid) -> Result<doc::Model> {
    doc::Entity::find_by_id(id)
        .lock_exclusive()
        .one(txn)
        .await?
        .ok_or_else(|| Error::NotFound(format!("stock movement {id}")))
}

async fn load_lines<C: ConnectionTrait>(conn: &C, move_id: Uuid) -> Result<Vec<line::Model>> {
    line::Entity::find()
        .filter(line::Column::MoveId.eq(move_id))
        .order_by_asc(line::Column::LineNo)
        .all(conn)
        .await
        .map_err(Error::from)
}

/// The items on a set of lines, plus their stock UoMs.
async fn load_items<C: ConnectionTrait>(
    conn: &C,
    lines: &[line::Model],
) -> Result<(HashMap<Uuid, item::item::Model>, HashMap<Uuid, uom::Model>)> {
    let ids: Vec<Uuid> = lines.iter().map(|l| l.item_id).collect();
    let items: HashMap<Uuid, item::item::Model> = item::item::Entity::find()
        .filter(item::item::Column::Id.is_in(ids))
        .all(conn)
        .await?
        .into_iter()
        .map(|i| (i.id, i))
        .collect();
    for l in lines {
        if !items.contains_key(&l.item_id) {
            return Err(Error::NotFound(format!("item {}", l.item_id)));
        }
    }
    let uom_ids: Vec<Uuid> = items.values().map(|i| i.uom_id).collect();
    let uoms: HashMap<Uuid, uom::Model> = uom::Entity::find()
        .filter(uom::Column::Id.is_in(uom_ids))
        .all(conn)
        .await?
        .into_iter()
        .map(|u| (u.id, u))
        .collect();
    Ok((items, uoms))
}

// ---------------------------------------------------------------------------
// Views (API DTOs)
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct WarehouseRef {
    pub id: Uuid,
    pub code: String,
    pub name: String,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct MoveLineView {
    pub id: Uuid,
    pub line_no: i32,
    pub item_id: Uuid,
    pub sku: String,
    pub item_name: String,
    #[serde(with = "rust_decimal::serde::str")]
    #[schema(value_type = String)]
    pub qty: Decimal,
    #[serde(with = "rust_decimal::serde::str_option")]
    #[schema(value_type = Option<String>)]
    pub unit_cost: Option<Decimal>,
    pub memo: Option<String>,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct MoveView {
    pub id: Uuid,
    pub number: Option<String>,
    pub move_type: MoveType,
    #[schema(value_type = String, format = Date)]
    pub entry_date: chrono::NaiveDate,
    pub memo: String,
    pub reference: Option<String>,
    pub from_warehouse: Option<WarehouseRef>,
    pub to_warehouse: Option<WarehouseRef>,
    pub status: MoveStatus,
    /// Set when this document was generated by another (`module.doc:{id}`);
    /// such movements reverse only through their source.
    pub source: Option<String>,
    pub reverses_id: Option<Uuid>,
    pub reversed_by_id: Option<Uuid>,
    #[schema(value_type = Option<String>, format = DateTime)]
    pub posted_at: Option<chrono::DateTime<chrono::Utc>>,
    #[schema(value_type = String, format = DateTime)]
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub lines: Vec<MoveLineView>,
}

/// A row of the movement register (document without its lines).
#[derive(Serialize, utoipa::ToSchema)]
pub struct MoveHeader {
    pub id: Uuid,
    pub number: Option<String>,
    pub move_type: MoveType,
    #[schema(value_type = String, format = Date)]
    pub entry_date: chrono::NaiveDate,
    pub memo: String,
    pub reference: Option<String>,
    pub from_warehouse_id: Option<Uuid>,
    pub to_warehouse_id: Option<Uuid>,
    pub status: MoveStatus,
    pub source: Option<String>,
}

fn header(row: doc::Model) -> Result<MoveHeader> {
    Ok(MoveHeader {
        id: row.id,
        number: row.number,
        move_type: MoveType::parse(&row.move_type)?,
        entry_date: row.entry_date,
        memo: row.memo,
        reference: row.reference,
        from_warehouse_id: row.from_warehouse_id,
        to_warehouse_id: row.to_warehouse_id,
        status: MoveStatus::parse(&row.status)?,
        source: row.source,
    })
}

/// Register filters.
pub struct MoveFilter {
    pub move_type: Option<MoveType>,
    pub status: Option<MoveStatus>,
    pub warehouse_id: Option<Uuid>,
    pub from: Option<chrono::NaiveDate>,
    pub to: Option<chrono::NaiveDate>,
}

// ---------------------------------------------------------------------------
// HTTP surface
// ---------------------------------------------------------------------------

/// Adjustments have their own permission branch; everything else shares
/// the movements branch.
fn perm_view(t: MoveType) -> &'static str {
    match t {
        MoveType::Adjustment => names::ADJUSTMENTS_VIEW,
        _ => names::MOVEMENTS_VIEW,
    }
}

fn perm_create(t: MoveType) -> &'static str {
    match t {
        MoveType::Adjustment => names::ADJUSTMENTS_CREATE,
        _ => names::MOVEMENTS_CREATE,
    }
}

fn perm_post(t: MoveType) -> &'static str {
    match t {
        MoveType::Adjustment => names::ADJUSTMENTS_POST,
        _ => names::MOVEMENTS_POST,
    }
}

pub(crate) fn routes() -> Router {
    Router::new()
        .route("/inventory/moves", get(list_moves).post(create_move))
        .route(
            "/inventory/moves/{id}",
            get(get_move).put(update_move).delete(delete_move),
        )
        .route("/inventory/moves/{id}/post", post(post_move))
        .route("/inventory/moves/{id}/reverse", post(reverse_move))
}

pub(crate) fn api() -> utoipa::openapi::OpenApi {
    nebula::module::build_openapi(|| <ApiDoc as utoipa::OpenApi>::openapi())
}

#[derive(utoipa::OpenApi)]
#[openapi(paths(
    list_moves,
    get_move,
    create_move,
    update_move,
    delete_move,
    post_move,
    reverse_move
))]
struct ApiDoc;

#[derive(Deserialize, utoipa::ToSchema)]
pub struct MoveLineRequest {
    pub item_id: Uuid,
    /// Always positive, in the item's stock UoM. For adjustments this is
    /// the counted quantity (zero allowed).
    #[serde(with = "rust_decimal::serde::str")]
    #[schema(value_type = String)]
    pub qty: Decimal,
    /// Required per line when posting a receipt; optional cost override
    /// for an adjustment counting up (required up from zero). Issues and
    /// transfers must not send one.
    #[serde(default, with = "rust_decimal::serde::str_option")]
    #[schema(value_type = Option<String>)]
    pub unit_cost: Option<Decimal>,
    pub entered_uom_id: Option<Uuid>,
    pub memo: Option<String>,
}

#[derive(Deserialize, utoipa::ToSchema)]
pub struct CreateMoveRequest {
    pub move_type: MoveType,
    #[schema(value_type = String, format = Date)]
    pub entry_date: chrono::NaiveDate,
    pub memo: String,
    pub reference: Option<String>,
    /// Source warehouse: issues and transfers; for adjustments, the
    /// warehouse being counted.
    pub from_warehouse_id: Option<Uuid>,
    /// Destination warehouse: receipts and transfers.
    pub to_warehouse_id: Option<Uuid>,
    pub lines: Vec<MoveLineRequest>,
}

#[derive(Deserialize, utoipa::ToSchema)]
pub struct ReverseMoveRequest {
    #[serde(default)]
    pub reason: String,
    /// The reversal's date; defaults to today, never before the original.
    #[schema(value_type = Option<String>, format = Date)]
    pub entry_date: Option<chrono::NaiveDate>,
}

#[derive(Deserialize, utoipa::IntoParams)]
pub struct ListMovesQuery {
    pub move_type: Option<MoveType>,
    pub status: Option<MoveStatus>,
    /// Matches either side of the document.
    pub warehouse_id: Option<Uuid>,
    /// Entry date range, inclusive.
    pub from: Option<chrono::NaiveDate>,
    pub to: Option<chrono::NaiveDate>,
}

/// Map a request body onto the service input.
fn new_move(req: CreateMoveRequest, created_by: Option<Uuid>) -> NewMove {
    NewMove {
        move_type: req.move_type,
        entry_date: req.entry_date,
        memo: req.memo,
        reference: req.reference,
        from_warehouse_id: req.from_warehouse_id,
        to_warehouse_id: req.to_warehouse_id,
        lines: req
            .lines
            .into_iter()
            .map(|l| LineInput {
                item_id: l.item_id,
                qty: l.qty,
                unit_cost: l.unit_cost,
                entered_uom_id: l.entered_uom_id,
                memo: l.memo,
            })
            .collect(),
        created_by,
    }
}

#[utoipa::path(get, path = "/inventory/moves", tag = "inventory",
    params(ListMovesQuery),
    responses((status = 200, body = Vec<MoveHeader>)))]
async fn list_moves(
    authz: Authz,
    TenantDb(db): TenantDb,
    Query(q): Query<ListMovesQuery>,
) -> Result<Json<Vec<MoveHeader>>> {
    authz.require(names::MOVEMENTS_VIEW).await?;
    MoveService::new(db)
        .list(MoveFilter {
            move_type: q.move_type,
            status: q.status,
            warehouse_id: q.warehouse_id,
            from: q.from,
            to: q.to,
        })
        .await
        .map(Json)
}

#[utoipa::path(get, path = "/inventory/moves/{id}", tag = "inventory",
    params(("id" = Uuid, Path, description = "Movement id")),
    responses((status = 200, body = MoveView)))]
async fn get_move(
    authz: Authz,
    TenantDb(db): TenantDb,
    Path(id): Path<Uuid>,
) -> Result<Json<MoveView>> {
    let view = MoveService::new(db).view(id).await?;
    authz.require(perm_view(view.move_type)).await?;
    Ok(Json(view))
}

#[utoipa::path(post, path = "/inventory/moves", tag = "inventory",
    request_body = CreateMoveRequest,
    responses((status = 200, body = MoveView)))]
async fn create_move(
    authz: Authz,
    audit: Audit,
    TenantDb(db): TenantDb,
    Json(req): Json<CreateMoveRequest>,
) -> Result<Json<MoveView>> {
    authz.require(perm_create(req.move_type)).await?;
    let view = MoveService::new(db)
        .create_draft(new_move(req, Some(authz.user.id)))
        .await?;
    audit.0.created("scm.move", view.id, &view).await;
    Ok(Json(view))
}

#[utoipa::path(put, path = "/inventory/moves/{id}", tag = "inventory",
    params(("id" = Uuid, Path, description = "Movement id")),
    request_body = CreateMoveRequest,
    responses((status = 200, body = MoveView)))]
async fn update_move(
    authz: Authz,
    audit: Audit,
    TenantDb(db): TenantDb,
    Path(id): Path<Uuid>,
    Json(req): Json<CreateMoveRequest>,
) -> Result<Json<MoveView>> {
    let service = MoveService::new(db);
    authz.require(perm_create(service.move_type_of(id).await?)).await?;
    let before = service.view(id).await?;
    let after = service.update_draft(id, new_move(req, None)).await?;
    audit.0.updated("scm.move", id, &before, &after).await;
    Ok(Json(after))
}

#[utoipa::path(delete, path = "/inventory/moves/{id}", tag = "inventory",
    params(("id" = Uuid, Path, description = "Movement id")),
    responses((status = 200, body = MoveView)))]
async fn delete_move(
    authz: Authz,
    audit: Audit,
    TenantDb(db): TenantDb,
    Path(id): Path<Uuid>,
) -> Result<Json<MoveView>> {
    let service = MoveService::new(db);
    authz.require(perm_create(service.move_type_of(id).await?)).await?;
    let view = service.delete_draft(id).await?;
    audit.0.deleted("scm.move", view.id, &view).await;
    Ok(Json(view))
}

#[utoipa::path(post, path = "/inventory/moves/{id}/post", tag = "inventory",
    params(("id" = Uuid, Path, description = "Movement id")),
    responses((status = 200, body = MoveView)))]
async fn post_move(
    authz: Authz,
    audit: Audit,
    TenantDb(db): TenantDb,
    Extension(numbering): Extension<Numbering>,
    Path(id): Path<Uuid>,
) -> Result<Json<MoveView>> {
    let service = MoveService::new(db);
    authz.require(perm_post(service.move_type_of(id).await?)).await?;
    let view = service.post(id, &numbering).await?;
    audit
        .0
        .event(format!(
            "posted stock movement {}",
            view.number.as_deref().unwrap_or("")
        ))
        .await;
    Ok(Json(view))
}

#[utoipa::path(post, path = "/inventory/moves/{id}/reverse", tag = "inventory",
    params(("id" = Uuid, Path, description = "Movement id")),
    request_body = ReverseMoveRequest,
    responses((status = 200, body = MoveView)))]
async fn reverse_move(
    authz: Authz,
    audit: Audit,
    TenantDb(db): TenantDb,
    Extension(numbering): Extension<Numbering>,
    Path(id): Path<Uuid>,
    Json(req): Json<ReverseMoveRequest>,
) -> Result<Json<MoveView>> {
    authz.require(names::MOVEMENTS_REVERSE).await?;
    let view = MoveService::new(db)
        .reverse(
            id,
            &req.reason,
            req.entry_date,
            &numbering,
            Some(authz.user.id),
        )
        .await?;
    audit
        .0
        .event(format!(
            "reversed stock movement with {}",
            view.number.as_deref().unwrap_or("")
        ))
        .await;
    Ok(Json(view))
}
